### ISSUE TITLE
Crash when omnisql sends unauthorized commands to the server

### ISSUE THREAD

**Issue by gshimansky** [heavyai/heavydb#402]
Steps to reproduce:

1. Checkout and build omniscidb. I built revision 73fa570ed73cc1689088018befea3a4b068c192a.
2. Launch server with `../startomnisci`.
3. Launch `omnisql` with command `build/bin/omnisql`.
4. Enter some garbage for password. Client gives message `Invalid credentials.` but still allows to send commands.
5. Give some command, e.g. `\u` or `\l`. Server crashes.
6. For `\u` I get the following stack trace:
```
Thread 6 "omnisci_server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fd3045d2700 (LWP 18579)]
0x000055f03a198c32 in MapDHandler::get_users(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
(gdb) bt
#0  0x000055f03a198c32 in MapDHandler::get_users(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#1  0x000055f03a0e511d in MapDProcessor::process_get_users(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*) ()
#2  0x000055f03a12b96f in MapDProcessor::dispatchCall(apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, void*) ()
#3  0x000055f03a132098 in apache::thrift::TDispatchProcessor::process(std::shared_ptr<apache::thrift::protocol::TProtocol>, std::shared_ptr<apache::thrift::protocol::TProtocol>, void*) ()
#4  0x00007fd30ad0232b in apache::thrift::server::TConnectedClient::run() ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#5  0x00007fd30ad082a5 in apache::thrift::server::TThreadedServer::TConnectedClientRunner::run() ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#6  0x00007fd30ad19f0d in apache::thrift::concurrency::PthreadThread::threadMain(void*) ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#7  0x00007fd30a871182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007fd30a79ab1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by psilvest** [comment]
This issue has been inactive for a while, and the project has changed substantially. If this still occurs on the latest release, please add reproduction steps and environment details.
