### ISSUE TITLE
SQLImporter problem

### ISSUE THREAD

**Issue by ggcking** [heavyai/heavydb#458]
hi, I use SQLImporter import 70millions records table through jdbc,  the exception is
TException failed - org.apache.thrift.transport.TTransportException
org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77)
	at com.mapd.thrift.server.MapD$Client.recv_load_table_binary_columnar(MapD.java:1723)
	at com.mapd.thrift.server.MapD$Client.load_table_binary_columnar(MapD.java:1708)
    ....
but I try serveral times, it can work. what's the problem? how to solove it.

**Comment by randyzwitch** [comment]
Can you provide more details? The table schema would be helpful, along with whether you are letting SQLImporter create the table in OmniSci vs. hand-writing the DDL.

**Comment by psilvest** [comment]
This issue has been inactive for a while, and the project has changed substantially. If this still occurs on the latest release, please add reproduction steps and environment details.
