### ISSUE TITLE
Crash when selected database doesn't exist

### ISSUE THREAD

**Issue by gshimansky** [heavyai/heavydb#459]
I run omniscidb server like this:

```
./bin/omnisci_server data --port 62074 --http-port 62078 --calcite-port 62079 --config omnisci.conf --verbose
```
on freshly initialized data directory. If I run `omnisql` client with a database other than `omnisci`, it allows me to connect, but when I issue "list databases" command `\l`, it crashes:
```
bin/omnisql --port 62074 ibis_testing -u admin -p HyperInteractive
```
Stack trace looks like this:
```
#0  std::__atomic_base<bool>::load (__m=std::memory_order_seq_cst, this=0x68)
    at /usr/include/c++/8/bits/atomic_base.h:396
#1  std::atomic<bool>::operator bool (this=0x68) at /usr/include/c++/8/atomic:86
#2  0x00005620af8c7641 in Catalog_Namespace::SysCatalog::checkPrivileges (
    this=0x5620b4b07360 <Catalog_Namespace::SysCatalog::instance()::sys_cat>, user=...,
    privObjects=std::vector of length 1, capacity 1 = {...})
    at /nfs/site/home/gashiman/work/omniscidb/Catalog/SysCatalog.cpp:1787
#3  0x00005620af8c2b06 in Catalog_Namespace::SysCatalog::getDatabaseListForUser[abi:cxx11](Catalog_Namespace::UserMetadata const&) (this=0x5620b4b07360 <Catalog_Namespace::SysCatalog::instance()::sys_cat>, user=...)
    at /nfs/site/home/gashiman/work/omniscidb/Catalog/SysCatalog.cpp:1305
#4  0x00005620af72f75d in MapDHandler::get_databases (this=0x5620b553fae0, dbinfos=
    std::vector of length 0, capacity 0, session="")
    at /nfs/site/home/gashiman/work/omniscidb/ThriftHandler/MapDHandler.cpp:2142
#5  0x00005620af637b6c in MapDProcessor::process_get_databases (this=0x5620b5551a60, seqid=0, iprot=0x7fc5e80011f0,
    oprot=0x7fc5e8001660, callContext=0x0) at /nfs/site/home/gashiman/work/omniscidb/debug/gen-cpp/MapD.cpp:24133
#6  0x00005620af63041e in MapDProcessor::dispatchCall (this=0x5620b5551a60, iprot=0x7fc5e80011f0,
    oprot=0x7fc5e8001660, fname="get_databases", seqid=0, callContext=0x0)
    at /nfs/site/home/gashiman/work/omniscidb/debug/gen-cpp/MapD.cpp:23310
#7  0x00005620af5a93fa in apache::thrift::TDispatchProcessor::process (this=0x5620b5551a60,
    in=std::shared_ptr<apache::thrift::protocol::TProtocol> (use count 2, weak count 0) = {...},
    out=std::shared_ptr<apache::thrift::protocol::TProtocol> (use count 2, weak count 0) = {...},
    connectionContext=0x0) at /usr/local/mapd-deps/lib/../include/thrift/TDispatchProcessor.h:121
#8  0x00007fc5f6df132b in apache::thrift::server::TConnectedClient::run() ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#9  0x00007fc5f6df72a5 in apache::thrift::server::TThreadedServer::TConnectedClientRunner::run() ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#10 0x00007fc5f6e08f0d in apache::thrift::concurrency::PthreadThread::threadMain(void*) ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#11 0x00007fc5f695e182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#12 0x00007fc5f6887b1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
On line `/nfs/site/home/gashiman/work/omniscidb/Catalog/SysCatalog.cpp:1787` variable `user` is not initialized.

**Comment by psilvest** [comment]
This issue has been inactive for a while, and the project has changed substantially. If this still occurs on the latest release, please add reproduction steps and environment details.
