### ISSUE TITLE
Crash on left join

### ISSUE THREAD

**Issue by gshimansky** [heavyai/heavydb#463]
The following is an excerpt from Ibis tests which reliably result in a crash for me. Using omniscidb master branch debug build 1dac507f6e1efb70b0addf0b82cef119fcccb94a
```
CREATE TABLE table1 (
playerID TEXT ENCODING DICT(32),
yearID BIGINT,
stint BIGINT,
teamID TEXT ENCODING DICT(32),
lgID TEXT ENCODING DICT(32),
G BIGINT,
AB BIGINT,
R BIGINT,
H BIGINT,
X2B BIGINT,
X3B BIGINT,
HR BIGINT,
RBI BIGINT,
SB BIGINT,
CS BIGINT,
BB BIGINT,
SO BIGINT,
IBB BIGINT,
HBP BIGINT,
SH BIGINT,
SF BIGINT,
GIDP BIGINT);

INSERT INTO table1 VALUES ('keefeti01',1880,1,'TRN','NL',12,43,4,10,3,0,0,3,0,0,1,12,0,0,0,0,0);

CREATE TABLE table2 (
playerID TEXT ENCODING DICT(32),
awardID TEXT ENCODING DICT(32),
yearID BIGINT,
lgID TEXT ENCODING DICT(32),
tie TEXT ENCODING DICT(32),
notes TEXT ENCODING DICT(32));

INSERT INTO table2 VALUES ('keefeti01','Pitching Triple Crown',1888,'NL',0,0);

SELECT t0.*
FROM (
  SELECT *
  FROM table1
  WHERE "yearID" = 2015
) t0
  LEFT JOIN (
    SELECT "playerID", "awardID", "tie", "notes"
    FROM (
      SELECT *
      FROM table2
      WHERE "lgID" = 'NL'
    ) t2
  ) t1
    ON t0."playerID" = t1."playerID";
```

Crash happens with failed assertion: `2019-12-11T16:08:43.715894 F 26160 StringDictionaryProxy.cpp:68 Check failed: generation_ >= 0 (-1 >= 0)`. Stack trace looks like this:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4aa3899 in __GI_abort () at abort.c:79
#2  0x00005555573e9d40 in logger::Logger::~Logger (this=0x7ffe57f0d350, __in_chrg=<optimized out>)
    at /nfs/site/home/gashiman/work/omniscidb/Shared/Logger.cpp:383
#3  0x0000555559f30897 in StringDictionaryProxy::getIdOfString (this=0x7fffc8007b70, str="keefeti01")
    at /nfs/site/home/gashiman/work/omniscidb/StringDictionary/StringDictionaryProxy.cpp:68
#4  0x0000555557aff195 in (anonymous namespace)::translate_str_id_to_outer_dict (elem=0, min_elem=0, max_elem=0,
    sd_inner_proxy=0x7fffc8007e80, sd_outer_proxy=0x7fffc8007b70)
    at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/HashJoinRuntime.cpp:80
#5  0x0000555557aff3b0 in fill_hash_join_buff_impl<fill_hash_join_buff_bucketized(int32_t*, int32_t, JoinColumn, JoinColumnTypeInfo, void const*, void const*, int32_t, int32_t, int64_t)::<lambda(auto:23)> >(int32_t *, int32_t, JoinColumn, JoinColumnTypeInfo, const void *, const void *, int32_t, int32_t, <lambda(auto:23)>) (buff=0x7fffc800a290,
    invalid_slot_val=-1, join_column=..., type_info=..., sd_inner_proxy=0x7fffc8007e80,
    sd_outer_proxy=0x7fffc8007b70, cpu_thread_idx=0, cpu_thread_count=176, slot_sel=...)
    at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/HashJoinRuntime.cpp:142
#6  0x0000555557aff603 in fill_hash_join_buff_bucketized (buff=0x7fffc800a290, invalid_slot_val=-1,
    join_column=..., type_info=..., sd_inner_proxy=0x7fffc8007e80, sd_outer_proxy=0x7fffc8007b70, cpu_thread_idx=0,
    cpu_thread_count=176, bucket_normalization=1)
    at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/HashJoinRuntime.cpp:173
#7  0x0000555557ae6bbb in JoinHashTable::<lambda()>::operator()(void) const (__closure=0x7fffc8008388)
    at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/JoinHashTable.cpp:846
#8  0x0000555557aedc85 in std::__invoke_impl<void, JoinHashTable::initHashTableOnCpu(const int8_t*, size_t, const std::pair<const Analyzer::ColumnVar*, const Analyzer::Expr*>&, HashEntryInfo, int32_t)::<lambda()> >(std::__invoke_other, JoinHashTable::<lambda()> &&) (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#9  0x0000555557aedbe7 in std::__invoke<JoinHashTable::initHashTableOnCpu(const int8_t*, size_t, const std::pair<const Analyzer::ColumnVar*, const Analyzer::Expr*>&, HashEntryInfo, int32_t)::<lambda()> >(JoinHashTable::<lambda()> &&)
    (__fn=...) at /usr/include/c++/9/bits/invoke.h:95
#10 0x0000555557aedb68 in std::thread::_Invoker<std::tuple<JoinHashTable::initHashTableOnCpu(const int8_t*, size_t, const std::pair<const Analyzer::ColumnVar*, const Analyzer::Expr*>&, HashEntryInfo, int32_t)::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x7fffc8008388) at /usr/include/c++/9/thread:244
#11 0x0000555557aedb24 in std::thread::_Invoker<std::tuple<JoinHashTable::initHashTableOnCpu(const int8_t*, size_t, const std::pair<const Analyzer::ColumnVar*, const Analyzer::Expr*>&, HashEntryInfo, int32_t)::<lambda()> > >::operator()(void) (this=0x7fffc8008388) at /usr/include/c++/9/thread:251
#12 0x0000555557aedae4 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<JoinHashTable::initHashTableOnCpu(const int8_t*, size_t, const std::pair<const Analyzer::ColumnVar*, const Analyzer::Expr*>&, HashEntryInfo, int32_t)::<lambda()> > > >::_M_run(void) (this=0x7fffc8008380) at /usr/include/c++/9/thread:195
#13 0x00007ffff4ed3f74 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007ffff4c78669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#15 0x00007ffff4ba0323 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by psilvest** [comment]
This issue has been inactive for a while, and the project has changed substantially. If this still occurs on the latest release, please add reproduction steps and environment details.
