### ISSUE TITLE
Failed assertion (crash) in SQL function TRIM

### ISSUE THREAD

**Issue by gshimansky** [heavyai/heavydb#485]
The following code leads to a crash.

```
CREATE TABLE table2 (
bigint_col BIGINT,
string_col TEXT ENCODING DICT(32));
SELECT trim("string_col") AS tmp FROM table2;
```
Server prints this message:
`2020-01-08T15:00:02.879711 F 53613 RelAlgAbstractInterpreter.cpp:2182 Check failed: !query_ast.HasParseError()`

Using debug build 1dac507f6e1efb70b0addf0b82cef119fcccb94a on Ubuntu 19.10, gcc 9.2.1.

Stack trace looks like this:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f8707033899 in __GI_abort () at abort.c:79
#2  0x0000562de3985d40 in logger::Logger::~Logger (this=0x7f8700e89a00, __in_chrg=<optimized out>)
    at /nfs/site/home/gashiman/work/omniscidb/Shared/Logger.cpp:383
#3  0x0000562de3dc7550 in deserialize_ra_dag (
    query_ra="{\n  \"rels\": [\n    {\n      \"id\": \"0\",\n      \"relOp\": \"EnumerableTableScan\",\n      \"fieldNames\": [\n        \"index\",\n        \"Unnamed__0\",\n        \"id\",\n        \"bool_col\",\n        \"tinyint_col\",\n       "..., cat=..., ra_executor=0x7f8700e8a3a0, render_opts=0x0)
    at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/RelAlgAbstractInterpreter.cpp:2182
#4  0x0000562de3e11d54 in RelAlgExecutor::executeRelAlgQueryNoRetry (this=0x7f8700e8a3a0,
    query_ra="{\n  \"rels\": [\n    {\n      \"id\": \"0\",\n      \"relOp\": \"EnumerableTableScan\",\n      \"fieldNames\": [\n        \"index\",\n        \"Unnamed__0\",\n        \"id\",\n        \"bool_col\",\n        \"tinyint_col\",\n       "..., co=..., eo=..., render_info=0x0) at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/RelAlgExecutor.cpp:100
#5  0x0000562de3e118bf in RelAlgExecutor::executeRelAlgQuery (this=0x7f8700e8a3a0,
    query_ra="{\n  \"rels\": [\n    {\n      \"id\": \"0\",\n      \"relOp\": \"EnumerableTableScan\",\n      \"fieldNames\": [\n        \"index\",\n        \"Unnamed__0\",\n        \"id\",\n        \"bool_col\",\n        \"tinyint_col\",\n       "..., co=..., eo=..., render_info=0x0) at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/RelAlgExecutor.cpp:73
#6  0x0000562de38aced3 in MapDHandler::<lambda()>::operator()(void) const (__closure=0x7f8700e8a110)
    at /nfs/site/home/gashiman/work/omniscidb/ThriftHandler/MapDHandler.cpp:4510
#7  0x0000562de38bb3fb in measure<std::chrono::duration<long, std::ratio<1, 1000> > >::execution<MapDHandler::execute_rel_alg(TQueryResult&, query_state::QueryStateProxy, const string&, bool, ExecutorDeviceType, int32_t, int32_t, bool, bool, bool, bool, bool) const::<lambda()> >(MapDHandler::<lambda()>) (func=...)
    at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/../Shared/measure.h:32
#8  0x0000562de38ad472 in MapDHandler::execute_rel_alg (this=0x562dea189010, _return=..., query_state_proxy=...,
    query_ra="{\n  \"rels\": [\n    {\n      \"id\": \"0\",\n      \"relOp\": \"EnumerableTableScan\",\n      \"fieldNames\": [\n        \"index\",\n        \"Unnamed__0\",\n        \"id\",\n        \"bool_col\",\n        \"tinyint_col\",\n       "..., column_format=true, executor_device_type=ExecutorDeviceType::CPU, first_n=-1, at_most_n=-1,
    just_explain=false, just_validate=false, find_push_down_candidates=false, just_calcite_explain=false,
    explain_optimized_ir=false) at /nfs/site/home/gashiman/work/omniscidb/ThriftHandler/MapDHandler.cpp:4509
#9  0x0000562de38b2018 in MapDHandler::sql_execute_impl (this=0x562dea189010, _return=..., query_state_proxy=...,
    column_format=true, nonce="", executor_device_type=ExecutorDeviceType::CPU, first_n=-1, at_most_n=-1)
    at /nfs/site/home/gashiman/work/omniscidb/ThriftHandler/MapDHandler.cpp:4958
#10 0x0000562de38870f7 in MapDHandler::<lambda()>::operator()(void) const (__closure=0x7f8700e8af70)
    at /nfs/site/home/gashiman/work/omniscidb/ThriftHandler/MapDHandler.cpp:902
#11 0x0000562de38bafe6 in measure<std::chrono::duration<long, std::ratio<1, 1000> > >::execution<MapDHandler::sql_execute(TQueryResult&, const TSessionId&, const string&, bool, const string&, int32_t, int32_t)::<lambda()> >(MapDHandler::<lambda()>) (func=...) at /nfs/site/home/gashiman/work/omniscidb/QueryEngine/../Shared/measure.h:32
#12 0x0000562de3887730 in MapDHandler::sql_execute (this=0x562dea189010, _return=...,
    session="C6xof9BSAFXP7Hm8WGFc1d79MGRb6P4E",
    query_str="SELECT trim(\"string_col\") AS tmp\nFROM functional_alltypes", column_format=true, nonce="", first_n=-1,
    at_most_n=-1) at /nfs/site/home/gashiman/work/omniscidb/ThriftHandler/MapDHandler.cpp:901
#13 0x0000562de379794e in MapDProcessor::process_sql_execute (this=0x562dea19b9c0, seqid=0, iprot=0x7f86f8003ac0,
    oprot=0x7f86f8003b30, callContext=0x0) at /nfs/site/home/gashiman/work/omniscidb/debug/gen-cpp/MapD.cpp:24862
#14 0x0000562de3788d6a in MapDProcessor::dispatchCall (this=0x562dea19b9c0, iprot=0x7f86f8003ac0, oprot=0x7f86f8003b30,
    fname="sql_execute", seqid=0, callContext=0x0)
    at /nfs/site/home/gashiman/work/omniscidb/debug/gen-cpp/MapD.cpp:23310
#15 0x0000562de36feb92 in apache::thrift::TDispatchProcessor::process (this=0x562dea19b9c0,
    in=std::shared_ptr<class apache::thrift::protocol::TProtocol> (use count 2, weak count 0) = {...},
    out=std::shared_ptr<class apache::thrift::protocol::TProtocol> (use count 2, weak count 0) = {...},
    connectionContext=0x0) at /usr/local/mapd-deps/lib/../include/thrift/TDispatchProcessor.h:121
#16 0x00007f87076be98c in apache::thrift::server::TConnectedClient::run() ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#17 0x00007f87076c4e1f in apache::thrift::server::TThreadedServer::TConnectedClientRunner::run() ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#18 0x00007f87076d798d in apache::thrift::concurrency::PthreadThread::threadMain(void*) ()
   from /usr/local/mapd-deps/lib/libthrift-0.11.0.so
#19 0x00007f8707208669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#20 0x00007f8707130323 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by psilvest** [comment]
This issue has been inactive for a while, and the project has changed substantially. If this still occurs on the latest release, please add reproduction steps and environment details.
