### ISSUE TITLE
using @mapd/connector cannot connect by using "http" getting error_msg: 'Authentication failure'

### ISSUE THREAD

**Issue by vqalex** [heavyai/heavydb#587]
I tried everything but can't make @mapd/connector to work.

default creds are used

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6273"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "omnisci"
const password = process.env.PASSWORD || "HyperInteractive"

tried

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6273"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "admin"
const password = process.env.PASSWORD || "HyperInteractive"

the same problem:
omnisci_server[1144]: 2020-09-14T11:02:28.552896 E 1144 16 DBHandler.cpp:548 Authentication failure

Using omnisci enterprise trial (30 days)

cat omnisci.conf 
port = 6274
http-port = 6278
calcite-port = 6279
data = "/var/lib/omnisci/data"
null-div-by-zero = true

[web]
port = 6273
frontend = "/opt/omnisci/frontend"

first part of the connector:

/* eslint-disable */

const Connector = require("/home/home/node_modules/@mapd/connector/dist/node-connector.js")

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6278"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "omnisci"
const password = process.env.PASSWORD || "HyperInteractive"

// The total number of tweets from Columbia
const query = "SELECT count(*) AS n FROM candles_USD_BTC"
const query2 ="SELECT count(*) AS n FROM candles_USD_ETH"
const defaultQueryOptions = {}

const connector = new Connector()

connector
  .protocol(protocol)
  .host(hostname)
  .port(port)
  .dbName(database)
  .user(username)
  .password(password)
  .connectAsync()
  .then(session =>
    // now that we have a session open we can make some db calls:
    Promise.all([
      session.getDashboardsAsync(),
      session.getTablesAsync(),
      session.getFieldsAsync("flights_donotmodify"),
      session.queryAsync(query, defaultQueryOptions),
      session.queryAsync(query2, defaultQueryOptions)
    ])
  )

**Comment by andrewseidl** [comment]
Hi @vqalex , since you're using the Enterprise Trial, are you able to log in using Immerse? Try going to http://localhost:6273 .

**Comment by cdessanti** [comment]
@vqalex FWIK the username name isn't omnisci anymore; try to use admin

**Comment by vqalex** [comment]
admin is not working with "@mapd/connector", the same problem.  DBHandler.cpp:548 Authentication failure.

I can login into Immerse with admin creds with no issues.

mapd/connector:

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6273"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "admin"
const password = process.env.PASSWORD || "HyperInteractive"

**Comment by andrewseidl** [comment]
Which version are you using? I am unable to reproduce with the below code with omnisci 5.4.0 and @mapd/connector 5.2.0. You can get the version info at http://localhost:6273/version.txt

```
/* eslint-disable */

const Connector = require("/tmp/tmpd.1600113247.rHo/node_modules/@mapd/connector/dist/node-connector.js")

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6273"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "admin"
const password = process.env.PASSWORD || "HyperInteractive"

const query = "SELECT count(*) AS n FROM omnisci_states"
const query2 ="SELECT count(*) AS n FROM omnisci_countries"
const defaultQueryOptions = {}

const connector = new Connector()

connector
.protocol(protocol)
.host(hostname)
.port(port)
.dbName(database)
.user(username)
.password(password)
.connectAsync()
.then(session =>
// now that we have a session open we can make some db calls:

Promise.all([
session.getDashboardsAsync(),
session.getTablesAsync(),
session.queryAsync(query, defaultQueryOptions),
session.queryAsync(query2, defaultQueryOptions)
])
)
```

**Comment by vqalex** [comment]
OmniSciDB:
5.4.0-20200904-1b17b5c4e2

Immerse:
296-release-prod
4aa3476


Web Server:
25fefa9

**Comment by vqalex** [comment]
error, tried to install fresh Ubuntu 18.04 and everything from scratch 

home@home-MS-7A95:~$ node gpudp-connect.js 
Something bad happened:  TOmniSciException: TOmniSciException
    at OmniSci_connect_result.module.exports.OmniSci_connect_result.read (/home/home/node_modules/@mapd/connector/dist/node-connector.js:20380:2257)
    at module.exports.exports.Client.module.exports.OmniSciClient.recv_connect (/home/home/node_modules/@mapd/connector/dist/node-connector.js:20380:240831)
    at decodeCallback (/home/home/node_modules/@mapd/connector/dist/node-connector.js:3432:42)
    at /home/home/node_modules/@mapd/connector/dist/node-connector.js:964:6
    at IncomingMessage.<anonymous> (/home/home/node_modules/@mapd/connector/dist/node-connector.js:3488:47)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  error_msg: 'Authentication failure'
****

**Comment by vqalex** [comment]
I followed following installation guide twice, and only the problem I have is connecting using @mapd/connector

https://docs.omnisci.com/installation-and-configuration/installation/installing-on-ubuntu/ubuntu-apt-gpu-ee

**Comment by cdessanti** [comment]
> OmniSciDB:
> 5.4.0-20200904-1b17b5c4e2
> 
> Immerse:
> 296-release-prod
> 4aa3476
> 
> Web Server:
> 25fefa9
> 
> @mapd/connector@5.2.0

@vqalex 
In my opinion, your Environment works well; I cannot log in to a localhost DB using the admin user.

I had to create a new one (you can call as you want), then grants required privileges to the objects you needed and change your files with the new credentials

log to the database with omnisql, immerse, or another client then

`CREATE USER alex ( password 'Alex123' );
GRANT ALL ON DATABASE omnisci to alex;`

Now the example would run.

![image](https://user-images.githubusercontent.com/30822551/93200076-9acfad00-f74f-11ea-8898-1110ad685b2f.png)


@andrewseidl 
Have you tried with the admin user? I also got the authentication failure error; is it normal?

**Comment by vqalex** [comment]
Not sure how did you make it work,

CREATE USER alex ( password 'Alex123' ); GRANT ALL ON DATABASE omnisci to alex; --syntax error

created user

CREATE USER alex ( password = 'Alex123' );
GRANT ALL ON DATABASE omnisci to alex;
/* eslint-disable */

const Connector = require("../dist/node-connector.js")

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6273"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "alex"
const password = process.env.PASSWORD || "Alex123"

getting:

home@home-MS-7A95:~/test/node_modules/@mapd/connector/examples$ node node.js 
Something bad happened:  { TOmniSciException: TOmniSciException
    at OmniSci_connect_result.module.exports.OmniSci_connect_result.read (/home/home/test/node_modules/@mapd/connector/dist/node-connector.js:20380:2257)
    at module.exports.exports.Client.module.exports.OmniSciClient.recv_connect (/home/home/test/node_modules/@mapd/connector/dist/node-connector.js:20380:240831)
    at decodeCallback (/home/home/test/node_modules/@mapd/connector/dist/node-connector.js:3432:42)
    at /home/home/test/node_modules/@mapd/connector/dist/node-connector.js:964:6
    at IncomingMessage.<anonymous> (/home/home/test/node_modules/@mapd/connector/dist/node-connector.js:3488:47)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'TOmniSciException',
  message: 'TOmniSciException',
  error_msg: 'Authentication failure' }

and DB log
Sep 15 08:13:35 home-MS-7A95 omnisci_server[1138]: 2020-09-15T08:13:35.678528 E 1138 12 DBHandler.cpp:548 Authentication failure
Sep 15 08:13:37 home-MS-7A95 omnisci_server[1138]: 2020-09-15T08:13:37.907622 E 1138 12 DBHandler.cpp:548 Authentication failure

Please let me know if I should try other version of omnisci, mapd/connector or instead of Ubuntu use CentOS maybe..

**Comment by vqalex** [comment]
no luck, tried everything but still have the same problem. I will try to test with MapD 5.2.2

**Comment by vqalex** [comment]
@cdessanti should @mapd/connector@5.2.0 work with OpenSource version without Immerse, just direct connection to Backend HTTP: localhost:6278

**Comment by cdessanti** [comment]
> @cdessanti should @mapd/connector@5.2.0 work with OpenSource version without Immerse, just direct connection to Backend HTTP: localhost:6278

Yes, AFAIK, you have to authenticate against the database using HTTP or HTPPS protocol with this connector.
Also, Immerse is authenticating against the database, and I guess it's using mapd-connector toot

**Comment by vqalex** [comment]
@cdessanti @andrewseidl Guys, I still can't get it connected, tried different builds with the same result. DB works but can't connect with @mapd/connector. The last part is to try 4.x version.

Maybe I'm doing something wrong. Install/Builds of OmnisciDB is straight forward. This is what I'm doing:

This time old version 4.8.1 (tried all newer with the same result.

1. Start DB, Backend HTTP listens on 6278
2. npm install @mapd/connector
3. edit ~/node_modules/@mapd/connector/examples$ nano node.js 

const Connector = require("../dist/node-connector.js")

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6278"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "alex123"
const password = process.env.PASSWORD || "alex123"

4. run :~/node_modules/@mapd/connector/examples$ node node.js 
5. In OmnisciDb 4.8.1 instead of authentication error, I'm getting "Invalid credentials

Please let me know what possibly I'm doing wrong of it is something that may not working for a while and I need test out really old version of MapD

Screenshots:
![Screenshot from 2020-09-19 12-08-05](https://user-images.githubusercontent.com/42011553/93671460-2c515e80-fa71-11ea-9870-59e7f7adc721.png)
![Screenshot from 2020-09-19 12-09-48](https://user-images.githubusercontent.com/42011553/93671462-2e1b2200-fa71-11ea-9164-5da3a5775ee6.png)

**Comment by cdessanti** [comment]
Hi @vqalex ,

I'm not sure, but on my environment the variable USERNAME is already defined with the user I'm using in the system; as an example in my UBUNTU 18.04 Notebook is

```
candido@zion-legion:~$ echo $USERNAME
candido
```
I'm not an expert of node.js but maybe with the OS variable USERNAME already defined, it's not using "admin" as a user to log on into the database

**Comment by vqalex** [comment]
@cdessanti you brought exact problem, thx!

Basically if you run 

$ node
> process.env.PASSWORD
> process.env.USERNAME

will get: home@home-MS-7A95:~$ node
> process.env.PASSWORD
undefined
> process.env.USERNAME
'home'
"

you will see that node is reading Ubuntu variables

I was using old version of mapd but had the same problem until applied

$ export PASSWORD=HyperInteractive
$ export USERNAME=mapd 

then it reads it coirrectly

**Comment by psilvest** [comment]
This issue has been inactive for a while, and the project has changed substantially. If this still occurs on the latest release, please add reproduction steps and environment details.
